export const SCHEDULE_LIST_REQUEST = 'SCHEDULE_LIST_REQUEST'
export const SCHEDULE_LIST_SUCCESS = 'SCHEDULE_LIST_SUCCESS'
export const SCHEDULE_LIST_FAIL = 'SCHEDULE_LIST_FAIL'

export const SCHEDULE_LIST_DEVICE_REQUEST = 'SCHEDULE_LIST_DEVICE_REQUEST'
export const SCHEDULE_LIST_DEVICE_SUCCESS = 'SCHEDULE_LIST_DEVICE_SUCCESS'
export const SCHEDULE_LIST_DEVICE_FAIL = 'SCHEDULE_LIST_DEVICE_FAIL'

export const SCHEDULE_DETAILS_REQUEST = 'SCHEDULE_DETAILS_REQUEST'
export const SCHEDULE_DETAILS_SUCCESS = 'SCHEDULE_DETAILS_SUCCESS'
export const SCHEDULE_DETAILS_FAIL = 'SCHEDULE_DETAILS_FAIL'

export const SCHEDULE_DELETE_REQUEST = 'SCHEDULE_DELETE_REQUEST'
export const SCHEDULE_DELETE_SUCCESS = 'SCHEDULE_DELETE_SUCCESS'
export const SCHEDULE_DELETE_FAIL = 'SCHEDULE_DELETE_FAIL'

export const SCHEDULE_CREATE_REQUEST = 'SCHEDULE_CREATE_REQUEST'
export const SCHEDULE_CREATE_SUCCESS = 'SCHEDULE_CREATE_SUCCESS'
export const SCHEDULE_CREATE_FAIL = 'SCHEDULE_CREATE_FAIL'

export const SCHEDULE_UPDATE_REQUEST = 'SCHEDULE_UPDATE_REQUEST'
export const SCHEDULE_UPDATE_SUCCESS = 'SCHEDULE_UPDATE_SUCCESS'
export const SCHEDULE_UPDATE_FAIL = 'SCHEDULE_UPDATE_FAIL'



